plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "sh.hopme.driver"
    compileSdk = 34

    defaultConfig {
        minSdk = 29 // L2CAP CoC (createInsecureL2capChannel) requires API 29+
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = "1.8" }

    // Generated by android/build-aar.sh (gitignored):
    //   ../../../android/HopDemo/generated/kotlin/uniffi/hop_ffi/hop_ffi.kt   (the UniFFI bindings)
    //   ../../../android/HopDemo/generated/jniLibs/<abi>/libhop_ffi.so        (the native libraries)
    sourceSets["main"].java.srcDir("../../../android/HopDemo/generated/kotlin")
    sourceSets["main"].jniLibs.srcDir("../../../android/HopDemo/generated/jniLibs")
}

dependencies {
    // UniFFI-generated Kotlin uses JNA; the @aar variant bundles its native libs. `api` so the
    // generated `uniffi.hop.*` types stay usable from consumers (the app references them).
    api("net.java.dev.jna:jna:5.14.0@aar")

    // The bearer exposes Compose snapshot state (mutableStateOf/…), so the runtime is part of the
    // driver's public surface — `api` so consuming UI observes the same snapshot system.
    api(platform("androidx.compose:compose-bom:2024.06.00"))
    api("androidx.compose.runtime:runtime")

    // Cloud relay bearer: WebSocket (path B, wss:// → Cloud Run) + the okio ByteString it speaks.
    api("com.squareup.okhttp3:okhttp:4.12.0")

    implementation("androidx.core:core-ktx:1.13.1")

    // Shared cross-platform transport layer (ble-lab modules, wired in settings.gradle.kts). The
    // driver forms BLE (pure-L2CAP) + LAN links through these via one BearerManager; the legacy
    // in-driver transports were removed (this is now the only transport path).
    implementation(project(":hop-sdk"))
    implementation(project(":bearer-ble"))
    implementation(project(":bearer-lan"))
    // Cloud relay (WebSocket) shared bearer — one outbound link to the backbone, same node seam. Carries
    // OkHttp transitively (already a direct dep above); consumed only in prod, never in the ble-lab P2P room.
    // (No Wi-Fi Direct bearer: its per-peer connect-approval dialog is incompatible with a passive mesh.)
    implementation(project(":bearer-relay"))
}
