import org.gradle.testing.jacoco.plugins.JacocoTaskExtension
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    jacoco
}

// cov/android-driver: the driver suite runs under Robolectric, which re-defines the classes-under-test
// in its own sandbox classloader WITHOUT a source location. JaCoCo's on-the-fly agent SKIPS
// no-location classes by default, so without this the ~1150-line HopBearer executes under test but reads
// as 0% covered. includeNoLocationClasses = true makes the agent record them; the jdk.internal.* exclude
// avoids the JDK17 instrumentation crash that flag otherwise triggers.
tasks.withType<Test>().configureEach {
    configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = true
        excludes = listOf("jdk.internal.*")
    }
}

// cov/android-driver: analyze with the SAME JaCoCo the AGP coverage agent embeds (0.8.11). A version
// skew between the agent that writes the .exec and the report task that reads it makes the
// Robolectric-loaded classes resolve to 0% (their exec class-ids don't line up), even though AGP's own
// report shows them fully covered. Pinning the tool version keeps our excluding report/gate honest.
jacoco { toolVersion = "0.8.11" }

android {
    namespace = "sh.hopme.driver"
    // okhttp-android's AAR metadata (okhttp 5.4.0, below) requires compileSdk >= 36 from every consumer.
    compileSdk = 36

    defaultConfig {
        minSdk = 29 // L2CAP CoC (createInsecureL2capChannel) requires API 29+
    }

    // android-r2-01/-03/-05: the driver gates its test/automation + plaintext-mirror + verbose-log
    // surfaces on BuildConfig.DEBUG, so a release consumer strips them without a source flag. A
    // library's BuildConfig.DEBUG tracks the CONSUMING app's build type (debug lib for a debug app,
    // release lib for a release app), so a release APK compiles with these affordances gone.
    buildFeatures { buildConfig = true }

    // quality-cov: JVM unit-test line coverage (AGP wires jacoco + createDebugUnitTestCoverageReport).
    buildTypes { debug { enableUnitTestCoverage = true } }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    // quality-net-03: JVM unit tests for the pure driver logic (ContactBook JSON codec, LinkFlow
    // per-link counters). returnDefaultValues keeps any incidental android.jar stub call from throwing;
    // the real org.json (a testImplementation below) shadows the android stub so the contact-book codec
    // round-trips for real, not against a stub.
    // cov/android-driver: Robolectric now backs the full HopBearer instance suite, so it also needs the
    // merged Android resources/manifest, plus JNA pointed at the host libhop for the UniFFI free
    // functions the driver calls (addressBase58 / addressFromBase58 / decodeIdentity / serviceIdentify).
    testOptions {
        unitTests {
            isReturnDefaultValues = true
            isIncludeAndroidResources = true
            all { test ->
                // HOP_LIBDIR in CI (the generated host cdylib), else the repo's target/debug - build it
                // once with `cargo build -p hop`. JNA maps the plain name "hop" to libhop.{dylib,so} on
                // this search path, so the driver's free functions run against the REAL core in-JVM. The
                // Android jniLibs .so is never on the JVM classpath, so production is unaffected.
                val libDir = System.getenv("HOP_LIBDIR")
                    ?: file("../../../target/debug").absolutePath
                test.systemProperty("jna.library.path", libDir)
            }
        }
    }

    // Generated by tools/build-aar.sh (gitignored):
    //   ../../../apps/android/HopDemo/generated/kotlin/uniffi/hop_ffi/hop_ffi.kt   (the UniFFI bindings)
    //   ../../../apps/android/HopDemo/generated/jniLibs/<abi>/libhop_ffi.so        (the native libraries)
}
// AGP 9's restructured internal source-set classes no longer implement the classic (deprecated)
// com.android.build.gradle.api.AndroidLibrarySourceSet interface, so the old `sourceSets["main"].java.
// srcDir(...)` / `.jniLibs.srcDir(...)` pattern throws a ClassCastException under AGP 9.2.1 (confirmed
// locally). The androidComponents Variant API is the AGP-version-portable replacement (works unchanged
// under both this build's AGP 8.5.2 and apps/android/HopDemo's AGP 9.2.1) and applies to every variant, same
// as the old "main" source set did.
androidComponents {
    onVariants { variant ->
        variant.sources.java?.addStaticSourceDirectory("../../../apps/android/HopDemo/generated/kotlin")
        variant.sources.jniLibs?.addStaticSourceDirectory("../../../apps/android/HopDemo/generated/jniLibs")
    }
}
// Kotlin 2.x makes `android.kotlinOptions { jvmTarget = ... }` a hard compile error (moved to
// compilerOptions); this is the direct replacement, one level up from the `android {}` block.
kotlin { compilerOptions { jvmTarget.set(JvmTarget.JVM_1_8) } }

dependencies {
    // UniFFI-generated Kotlin uses JNA; the @aar variant bundles its native libs. `api` so the
    // generated `uniffi.hop.*` types stay usable from consumers (the app references them).
    api("net.java.dev.jna:jna:5.19.1@aar")

    // The bearer exposes Compose snapshot state (mutableStateOf/…), so the runtime is part of the
    // driver's public surface - `api` so consuming UI observes the same snapshot system. Kept in lockstep
    // with the app's compose-bom (below in apps/android/HopDemo/app) since both land in the same final APK's
    // dependency graph; only mutableStateOf/mutableStateListOf/mutableStateMapOf are used here (no
    // @Composable functions), so this module needs no Kotlin Compose compiler plugin.
    api(platform("androidx.compose:compose-bom:2026.06.01"))
    api("androidx.compose.runtime:runtime")

    // Cloud relay bearer: WebSocket (path B, wss:// → Cloud Run) + the okio ByteString it speaks.
    api("com.squareup.okhttp3:okhttp:5.4.0")

    // HELD at 1.13.1 (Dependabot PR #21 wants 1.19.0): androidx.core:core-ktx 1.19.0's AAR metadata hard-
    // requires AGP >= 9.1.0 and compileSdk >= 37 from every consumer (a real build failure, not a
    // warning, confirmed locally). :hop-driver is compiled by TWO independent Gradle builds - this one
    // (AGP 8.5.2, matching Kotlin Gradle Plugin 2.4.0's own documented max-supported AGP of 9.1.0) and
    // apps/android/HopDemo's (AGP 9.2.1) - so bumping core-ktx here would require also bumping this build's
    // whole AGP/Gradle toolchain, which no Dependabot PR requested and which is out of scope for this
    // migration. See the PR description for the held-PR note.
    implementation("androidx.core:core-ktx:1.13.1")

    // Shared cross-platform transport layer (ble-lab modules, wired in settings.gradle.kts). The
    // driver forms BLE (pure-L2CAP) + LAN links through these via one BearerManager; the legacy
    // in-driver transports were removed (this is now the only transport path).
    implementation(project(":hop-sdk"))
    implementation(project(":bearer-ble"))
    implementation(project(":bearer-lan"))
    // Cloud relay (WebSocket) shared bearer - one outbound link to the backbone, same node seam. Carries
    // OkHttp transitively (already a direct dep above); consumed only in prod, never in the ble-lab P2P room.
    // (No Wi-Fi Direct bearer: its per-peer connect-approval dialog is incompatible with a passive mesh.)
    implementation(project(":bearer-relay"))

    // quality-net-03: pure-logic unit tests. junit + the REAL org.json (shadows the android.jar stub so
    // ContactBook's JSON round-trip is exercised for real).
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20240303")

    // cov/android-driver: Robolectric shadows the Android framework (Context / SharedPreferences /
    // Handler+Looper / NotificationManager / Base64 / Log / File IO) so the ~1150-line HopBearer instance
    // and HopService run headless on the JVM - no device, no emulator.
    testImplementation("org.robolectric:robolectric:4.13")
    testImplementation("androidx.test:core:1.6.1")
    // The main `jna@aar` bundles only Android jnidispatch .so; the JVM test JVM needs the DESKTOP
    // jnidispatch (com/sun/jna/<os-arch>/libjnidispatch), which ships in the plain jar. This lets JNA
    // boot on the host so the driver's UniFFI free functions can call the real libhop (jna.library.path).
    testImplementation("net.java.dev.jna:jna:5.19.1")
    // MockWebServer backs the DoH (DNSSEC-chain) fetch test with a fake resolver, no real network. OkHttp 5
    // still publishes this legacy `mockwebserver` coordinate as a deprecated bridge over the OLD
    // okhttp3.mockwebserver package, so HopBearerDnssecTest's imports are unchanged.
    testImplementation("com.squareup.okhttp3:mockwebserver:5.4.0")
}

// quality-cov: line-coverage report over the DRIVER'S OWN Kotlin (sh.hopme.driver.**). The generated
// UniFFI JNA bindings (uniffi.hop.**, ~1500 lines under apps/android/HopDemo/generated) are third-party,
// machine-generated glue that is never unit-tested, so they are excluded from the denominator here -
// otherwise they alone drag the module to single digits regardless of how well the driver is covered.
// Reads the exec that AGP's enableUnitTestCoverage produces from testDebugUnitTest.
tasks.register<JacocoReport>("jacocoDriverReport") {
    dependsOn("testDebugUnitTest")
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    classDirectories.setFrom(driverCoverageClassDirs())
    sourceDirectories.setFrom(files("src/main/java"))
    executionData.setFrom(
        fileTree(buildDir) { include("outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec") },
    )
}

// cov/android-driver: the driver's own product classes that count toward coverage. Two exclusions from
// the denominator, both principled:
//   - uniffi/**        : machine-generated third-party UniFFI JNA glue (~1500 lines), never unit-tested.
//   - **/KeystoreSecret*: the AndroidKeyStore/StrongBox secure-element wrapper for the two long-term
//     device secrets (Ed25519 identity seed + SQLCipher db key). EVERY path calls a real TEE / secure
//     element (KeyStore.getInstance("AndroidKeyStore"), KeyGenerator "AndroidKeyStore",
//     KeyGenParameterSpec, StrongBoxUnavailableException) that does not exist / throws on a plain JVM and
//     is NOT Robolectric-backable. This is the same device-gated posture as the iOS Keychain identity/
//     db-key store (sec-priv-02) and is documented in CI as quality-net-r3-03: it is verified on-device
//     (identities preserved across reinstall), never in a JVM lane. Excluding it from the denominator is
//     the honest choice - we do not fake a secure element and then claim to have tested it.
fun driverCoverageClassDirs() = fileTree("${buildDir}/tmp/kotlin-classes/debug") {
    exclude("uniffi/**")
    exclude("**/KeystoreSecret*")
}

// cov/android-driver: hard 80% LINE floor over the same denominator as the report. Invoked from the
// `android` CI job so the driver's grade is ENFORCED (previously CI never ran any coverage task, so the
// number could silently rot). Fails the build if covered lines drop below 80%.
tasks.register<JacocoCoverageVerification>("jacocoDriverCoverageVerification") {
    dependsOn("testDebugUnitTest")
    classDirectories.setFrom(driverCoverageClassDirs())
    sourceDirectories.setFrom(files("src/main/java"))
    executionData.setFrom(
        fileTree(buildDir) { include("outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec") },
    )
    violationRules {
        rule {
            limit {
                counter = "LINE"
                value = "COVEREDRATIO"
                minimum = "0.80".toBigDecimal()
            }
        }
    }
}
