plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    jacoco
}

android {
    namespace = "sh.hopme.driver"
    compileSdk = 34

    defaultConfig {
        minSdk = 29 // L2CAP CoC (createInsecureL2capChannel) requires API 29+
    }

    // android-r2-01/-03/-05: the driver gates its test/automation + plaintext-mirror + verbose-log
    // surfaces on BuildConfig.DEBUG, so a release consumer strips them without a source flag. A
    // library's BuildConfig.DEBUG tracks the CONSUMING app's build type (debug lib for a debug app,
    // release lib for a release app), so a release APK compiles with these affordances gone.
    buildFeatures { buildConfig = true }

    // quality-cov: JVM unit-test line coverage (AGP wires jacoco + createDebugUnitTestCoverageReport).
    buildTypes { debug { enableUnitTestCoverage = true } }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = "1.8" }

    // quality-net-03: JVM unit tests for the pure driver logic (ContactBook JSON codec, LinkFlow
    // per-link counters). returnDefaultValues keeps any incidental android.jar stub call from throwing;
    // the real org.json (a testImplementation below) shadows the android stub so the contact-book codec
    // round-trips for real, not against a stub.
    testOptions { unitTests { isReturnDefaultValues = true } }

    // Generated by android/build-aar.sh (gitignored):
    //   ../../../android/HopDemo/generated/kotlin/uniffi/hop_ffi/hop_ffi.kt   (the UniFFI bindings)
    //   ../../../android/HopDemo/generated/jniLibs/<abi>/libhop_ffi.so        (the native libraries)
    sourceSets["main"].java.srcDir("../../../android/HopDemo/generated/kotlin")
    sourceSets["main"].jniLibs.srcDir("../../../android/HopDemo/generated/jniLibs")
}

dependencies {
    // UniFFI-generated Kotlin uses JNA; the @aar variant bundles its native libs. `api` so the
    // generated `uniffi.hop.*` types stay usable from consumers (the app references them).
    api("net.java.dev.jna:jna:5.14.0@aar")

    // The bearer exposes Compose snapshot state (mutableStateOf/…), so the runtime is part of the
    // driver's public surface — `api` so consuming UI observes the same snapshot system.
    api(platform("androidx.compose:compose-bom:2024.06.00"))
    api("androidx.compose.runtime:runtime")

    // Cloud relay bearer: WebSocket (path B, wss:// → Cloud Run) + the okio ByteString it speaks.
    api("com.squareup.okhttp3:okhttp:4.12.0")

    implementation("androidx.core:core-ktx:1.13.1")

    // Shared cross-platform transport layer (ble-lab modules, wired in settings.gradle.kts). The
    // driver forms BLE (pure-L2CAP) + LAN links through these via one BearerManager; the legacy
    // in-driver transports were removed (this is now the only transport path).
    implementation(project(":hop-sdk"))
    implementation(project(":bearer-ble"))
    implementation(project(":bearer-lan"))
    // Cloud relay (WebSocket) shared bearer — one outbound link to the backbone, same node seam. Carries
    // OkHttp transitively (already a direct dep above); consumed only in prod, never in the ble-lab P2P room.
    // (No Wi-Fi Direct bearer: its per-peer connect-approval dialog is incompatible with a passive mesh.)
    implementation(project(":bearer-relay"))

    // quality-net-03: pure-logic unit tests. junit + the REAL org.json (shadows the android.jar stub so
    // ContactBook's JSON round-trip is exercised for real).
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20240303")
}

// quality-cov: line-coverage report over the DRIVER'S OWN Kotlin (sh.hopme.driver.**). The generated
// UniFFI JNA bindings (uniffi.hop.**, ~1500 lines under android/HopDemo/generated) are third-party,
// machine-generated glue that is never unit-tested, so they are excluded from the denominator here —
// otherwise they alone drag the module to single digits regardless of how well the driver is covered.
// Reads the exec that AGP's enableUnitTestCoverage produces from testDebugUnitTest.
tasks.register<JacocoReport>("jacocoDriverReport") {
    dependsOn("testDebugUnitTest")
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    classDirectories.setFrom(
        fileTree("${buildDir}/tmp/kotlin-classes/debug") {
            exclude("uniffi/**")   // generated UniFFI bindings — not the driver's product code
        },
    )
    sourceDirectories.setFrom(files("src/main/java"))
    executionData.setFrom(
        fileTree(buildDir) { include("outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec") },
    )
}
